Repository CMPUT301F20T05/CriEngine, pull requests merged in 2020-11, with the labels that each got.

#93 fix: app flow is now correct
  client/app/src/main/AndroidManifest.xml
  client/app/src/main/java/com/example/criengine/Activities/BookActivity.java
  client/app/src/main/java/com/example/criengine/Activities/LoginActivity.java
  client/app/src/main/java/com/example/criengine/Activities/MainActivity.java
  client/app/src/main/java/com/example/criengine/Activities/MyBookActivity.java
  client/app/src/main/java/com/example/criengine/Activities/MyBooksActivity.java
  client/app/src/main/java/com/example/criengine/Activities/NotificationActivity.java
  client/app/src/main/java/com/example/criengine/Activities/RequestsForBookActivity.java
  client/app/src/main/java/com/example/criengine/Activities/RootActivity.java
  client/app/src/main/java/com/example/criengine/Adapters/MyBooksAdapter.java
  client/app/src/main/java/com/example/criengine/Adapters/RequestsForBookAdapter.java
  client/app/src/main/java/com/example/criengine/Fragments/BottomNavFragment.java
  client/app/src/main/java/com/example/criengine/Fragments/MyBooksListFragment.java
  client/app/src/main/res/layout/activity_add_book.xml
  client/app/src/main/res/layout/activity_login.xml
  client/app/src/main/res/layout/activity_my_book.xml
  client/app/src/main/res/layout/activity_my_books.xml
  client/app/src/main/res/layout/activity_notification.xml
  client/app/src/main/res/layout/list_format.xml
Labels: High Prioirty

#96 feat: add login intent tests
  client/app/build.gradle
  client/app/src/androidTest/java/com/example/criengine/LoginScreenTest.java
Labels: Tests

#110 fix: added all missing javaDocs
  client/app/src/main/java/com/example/criengine/Activities/AddBookActivity.java
  client/app/src/main/java/com/example/criengine/Activities/BookActivity.java
  client/app/src/main/java/com/example/criengine/Activities/LoginActivity.java
  client/app/src/main/java/com/example/criengine/Activities/MyBookActivity.java
  client/app/src/main/java/com/example/criengine/Activities/MyProfileActivity.java
  client/app/src/main/java/com/example/criengine/Activities/ProfileActivity.java
  client/app/src/main/java/com/example/criengine/Activities/RequestActivity.java
  client/app/src/main/java/com/example/criengine/Activities/RequestsForBookActivity.java
  client/app/src/main/java/com/example/criengine/Activities/RootActivity.java
  client/app/src/main/java/com/example/criengine/Activities/UserProfileActivity.java
  client/app/src/main/java/com/example/criengine/Adapters/BorrowerBooksListAdapter.java
  client/app/src/main/java/com/example/criengine/Adapters/MyBooksAdapter.java
  client/app/src/main/java/com/example/criengine/Adapters/NotificationAdapter.java
  client/app/src/main/java/com/example/criengine/Adapters/RequestsForBookAdapter.java
  client/app/src/main/java/com/example/criengine/Database/DatabaseWrapper.java
  client/app/src/main/java/com/example/criengine/Database/GoogleBooksWrapper.java
  client/app/src/main/java/com/example/criengine/Fragments/BottomNavFragment.java
  client/app/src/main/java/com/example/criengine/Fragments/MyBooksListFilterFragment.java
  client/app/src/main/java/com/example/criengine/Fragments/MyBooksListFragment.java
  client/app/src/main/java/com/example/criengine/Fragments/MyProfileFragment.java
  client/app/src/main/java/com/example/criengine/Fragments/NotificationFragment.java
  client/app/src/main/java/com/example/criengine/Fragments/ProfileFragment.java
  client/app/src/main/java/com/example/criengine/Fragments/RequestedBooksFragment.java
  client/app/src/main/java/com/example/criengine/Fragments/RootFragment.java
  client/app/src/main/java/com/example/criengine/Interfaces/IOnBackPressed.java
  client/app/src/test/java/com/example/criengine/BookUnitTest.java
  client/app/src/test/java/com/example/criengine/NotificationUnitTest.java
  client/app/src/test/java/com/example/criengine/ProfileUnitTest.java
Labels: Documentation

#109 feat: add intent tests for My-Books-List-Fragment
  client/app/src/androidTest/java/com/example/criengine/ExampleInstrumentedTest.java
  client/app/src/androidTest/java/com/example/criengine/MyBooksListTest.java
Labels: Tests

#113 feat: add a book intent tests
  client/app/src/androidTest/java/com/example/criengine/AddABookTest.java
Labels: Tests

#114 feat: add notifications intent test
  client/app/src/androidTest/java/com/example/criengine/NotificationTest.java
Labels: Tests

#115 feat: add my request intent tests
  client/app/src/androidTest/java/com/example/criengine/MyRequestTest.java
Labels: Tests

#116 feat: add my profile intent tests
  client/app/src/androidTest/java/com/example/criengine/MyProfileTest.java
Labels: Tests

#117 feat: add intent tests for view my book activity
  client/app/src/androidTest/java/com/example/criengine/ViewMyBookTest.java
Labels: Tests

#81 feat: add makeRequest, accept/rejectRequest
  client/app/src/main/java/com/example/criengine/Activities/AddBookActivity.java
  client/app/src/main/java/com/example/criengine/Activities/MyBookActivity.java
  client/app/src/main/java/com/example/criengine/Activities/MyProfileActivity.java
  client/app/src/main/java/com/example/criengine/Database/DatabaseWrapper.java
  client/app/src/main/java/com/example/criengine/Database/GoogleBooksWrapper.java
  client/app/src/main/java/com/example/criengine/Fragments/MyProfileFragment.java
  client/app/src/main/java/com/example/criengine/Fragments/RequestedBooksFragment.java
  client/app/src/main/java/com/example/criengine/Objects/Book.java
  client/app/src/main/java/com/example/criengine/Objects/Profile.java
  client/app/src/test/java/com/example/criengine/BookUnitTest.java
  client/app/src/test/java/com/example/criengine/ProfileUnitTest.java
Labels: DO NOT MERGE

#118 feat: profile intent tests
  client/app/src/androidTest/java/com/example/criengine/MyProfileFragmentTest.java
  client/app/src/androidTest/java/com/example/criengine/MyProfileTest.java
Labels: Tests

#106 feat: Scan-Add a book
  client/app/build.gradle
  client/app/src/main/AndroidManifest.xml
  client/app/src/main/java/com/example/criengine/Activities/AddBookActivity.java
  client/app/src/main/java/com/example/criengine/Activities/ScanActivity.java
  client/app/src/main/res/layout/activity_request.xml
  client/app/src/main/res/layout/activity_scan.xml
  client/app/src/main/res/menu/bottom_navigation_menu.xml
  client/app/src/main/res/values/strings.xml
Labels: WIP
